### ISSUE TITLE
Videos With Strange Characters In Title Won't Play

### ISSUE THREAD

**Issue by cuylerstuwe** [mindaugaskasp/discord-music-bot#10]
**Describe the bug**
Videos are downloaded with strange characters in the title included, and playback won't start (presumably because the module responsible for loading files can't read them).

**Screenshots**
![files with funky characters](https://i.imgur.com/BfKkujm.png)

**To Reproduce**
1. Start the bot.
2. Connect the bot to a voice channel.
3. Send message ```.get https://www.youtube.com/watch?v=oK8OkdsKXR8```.
4. Send message ```.play```.
5. Bot gives a "playing" response in Discord, but no audio plays in the voice channel and no errors appear in console.

**Expected behavior**
YouTube videos play regardless of whether their titles contain funky characters.

**Desktop (please complete the following information):**
 - OS: Mac OSX Mojave 10.14.3

**Related issues**:
Related to #8 , as both seem to be related to the translating data to the local filesystem.

**Comment by cuylerstuwe** [comment]
Pulled most recent version and reinstalled, seems to be working for now. Not sure whether the problem was related to older configuration or whether reproduction is more complicated than listed.

**Comment by mindaugaskasp** [comment]
Issue like this makes me consider to save downloaded files to local storage with some sort of hash name instead, which will avoid any weird utf characters. The downside it won't be as readable for local development, but it can be toggled, I suppose via config.

Again, thank you for your input, I really appreciate it :)

**Comment by cuylerstuwe** [comment]
Problem came back after adding a second video and trying to skip, now it won't play anything. No clue whether it's related to this or not -- it won't play anything now.

**Comment by cuylerstuwe** [comment]
Yeah, some sort of hash or at least character escaping might help.

**Comment by cuylerstuwe** [comment]
These are the errors I'm getting in the console when it's refusing to play now _(again, unsure whether it's related to the filenames or something else)_:

![console errors](https://i.imgur.com/8ek0IYJ.png)

**Comment by cuylerstuwe** [comment]
It does seem to be related to the filenames, though, because I haven't had any problems so far with any video whose name contains only filesystem-friendly characters.
