### ISSUE TITLE
Downloads are saved in project directory with backslash characters as part of the filename.

### ISSUE THREAD

**Issue by cuylerstuwe** [mindaugaskasp/discord-music-bot#8]
**Describe the bug**
Downloads are saved in project directory with backslash characters as part of the filename.

**To Reproduce**
1. Have the bot play a specific YouTube video that it hasn't played before.
2. File is downloaded into project directory rather than downloads sub-directory, with backslashes and other special characters as a part of the literal filename.

**Expected behavior**
File is stored in downloads directory, special characters are otherwise escaped.

**Screenshots**
![directory screenshot](https://i.imgur.com/3wfW2m9.png)

**Desktop (please complete the following information):**
 - Mac OSX Mojave 10.14.3

**Comment by mindaugaskasp** [comment]
Weird issue, I am running the app via docker on windows currently and can't reproduce it, I do get files in my `downloads` folder instead. Could this be filesystem nuances? I'll try to reproduce it on my mac later.
