### ISSUE TITLE
Bot allows "playing" audio twice, leading to a myriad of unexpected results.

### ISSUE THREAD

**Issue by cuylerstuwe** [mindaugaskasp/discord-music-bot#9]
**Describe the bug**
If the bot is sent a play command while already in a state where it's playing (or trying to play) audio, it will accept this command and this will lead to all sorts of weird behavior (stuttered warbly audio, error messages in console and nonsensical output in Discord, etc.).

**To Reproduce**
1. Have the bot join a channel.
2. Queue up a single YouTube video with the get command.
3. Send the bot a play command.
4. Send the bot another play command.
5. Discord channel plays a stuttered/warbly version of the audio, and the bot spazzes out in the text channel., either immediately or after some time (possibly depending on length of audio and/or Internet connection speed).

**Expected behavior**
If the play command is already playing something, prevent the user from playing again and inform the user via Discord messages that nothing will be done because a stream is already playing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OSX Mojave 10.14.3

**Additional context**
I found this bug when trying to play a long YouTube video. I'd assumed that it wasn't working on the the first attempt, so I tried again with a second play command. The second attempt played, but it cut short (possibly playing a partially-downoaded file?). Then, at some point (where the full file seems to have apparently been downloaded), the audio started playing, but warbly and choppy. It seems that the play process was being run twice, with the two instances of the process interacting with one another in strange ways.

**NOTE**: Possibly related to #7 , with the root issue from a user perspective being no indication of progress for downloading longer files before playing them back.

**Comment by mindaugaskasp** [comment]
Thank you for your feedback! 

I have noticed this issue myself today locally running the app and will investigate the issue asap.
